[package]
name = "timecard"
version = "0.2.0"
edition = "2024"
readme = "../README.md"
description = "Simple library that makes time tracking easier"
license = "MIT"
repository = "https://github.com/Stephen-Hamilton-C/timecard"

[lib]
name = "timecard"
path = "src/lib.rs"

[dependencies]
chrono = { workspace = true }
serde = { workspace = true }
thiserror = "2.0.18"
