name: Release

on:
  push:
    tags:
      - "v*"
      - "workflow-test"

permissions:
  contents: write

# TODO: Rebuild this from scratch - the action does not expect a Cargo workspace

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-24.04

    outputs:
      upload_url: ${{ steps.create.outputs.upload_url }}
      build_matrix: ${{ steps.create.outputs.build_matrix }}

    steps:
      - name: Publish crate
        id: create
        uses: seaofvoices/rust-release-action@v1
        with:
          release_tag: ${{ github.ref_name }}
          release_ref: ${{ github.ref_name }}
          publish_crate: false  # change to true once testing is done
          cargo_token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-artifacts:
    needs: release

    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.release.outputs.build_matrix) }}
    
    name: Build (${{ matrix.artifact-name }})
    runs-on: ${{ matrix.os }}

    steps:
      - name: Build artifact
        id: build
        uses: seaofvoices/rust-build-artifact-action@v1
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          package_name: ${{ matrix.name }}
          artifact_name: ${{ matrix.artifact_name }}
          cargo_target: ${{ matrix.name }}
          linker: ${{ matrix.linker }}
